# Generated by Django 4.0.4 on 2022-09-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0003_recipe_allergens_recipe_parentsubrecipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.IntegerField()),
                ('unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('nutritional_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jrecipes.nutritionalunit')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutritional_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jrecipes.nutritionalinfo'),
        ),
    ]
