# Generated by Django 4.0.4 on 2022-09-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0005_alter_nutritionalunit_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionalunit',
            name='serving_size',
        ),
        migrations.AddField(
            model_name='nutritionalinfo',
            name='serving_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
