# Generated by Django 4.0.4 on 2022-09-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0007_rename_serving_size_nutritionalinfo_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='parentSubRecipe',
            field=models.CharField(choices=[('recipe', 'Recipe'), ('subRecipe', 'Subrecipe'), ('ingredient', 'Ingredient')], default='recipe', max_length=20),
        ),
    ]
