# Generated by Django 4.0.4 on 2022-09-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0008_alter_recipe_parentsubrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='parentSubRecipe',
            field=models.CharField(choices=[('recipedsdsd', 'Recipe'), ('subRecipedsdsds', 'Subrecipe'), ('ingredientsdsds', 'Ingredient')], default='recipedsdsd', max_length=20),
        ),
    ]
