# Generated by Django 4.0.4 on 2022-09-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0010_alter_recipe_parentsubrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='unit',
            field=models.CharField(choices=[('milligram', 'mg'), ('g', 'Gram'), ('kg', 'Kilogram')], max_length=10),
        ),
    ]
