# Generated by Django 4.0.4 on 2022-09-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0011_alter_nutritionalinfo_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='unit',
            field=models.CharField(choices=[('milligram', 'mg'), ('gram', 'g'), ('kilogram', 'kg'), ('milliliter', 'ml'), ('liter', 'l'), ('tablespoon', 'tbsp'), ('pound', 'lb'), ('ounce', 'oz')], max_length=10),
        ),
    ]
