# Generated by Django 4.0.4 on 2022-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0012_alter_nutritionalinfo_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='portion_size',
            new_name='servings',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='parentSubRecipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='type_enum',
            field=models.CharField(choices=[('recipe', 'Recipe'), ('subRecipe', 'Recipe and ingredient'), ('ingredient', 'Ingredient')], default='recipe', max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='unit',
            field=models.CharField(choices=[('milligram', 'mg'), ('gram', 'g'), ('kilogram', 'Kg'), ('milliliter', 'mL'), ('liter', 'L'), ('pound', 'lb'), ('ounce', 'oz'), ('fluid_once', 'fl oz'), ('teaspoon', 'tsp'), ('tablespoon', 'Tbsp'), ('cup', 'cup'), ('pint', 'pint'), ('quart', 'quart'), ('gallon', 'gallon')], max_length=20),
        ),
    ]
