# Generated by Django 4.0.4 on 2023-01-03 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0014_instructionstep_instruction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('allergen', models.ManyToManyField(blank=True, to='jrecipes.allergen')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IngredientListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('unit', 'un'), ('milligram', 'mg'), ('gram', 'g'), ('kilogram', 'Kg'), ('milliliter', 'mL'), ('liter', 'L'), ('pound', 'lb'), ('ounce', 'oz'), ('fluid_once', 'fl oz'), ('teaspoon', 'tsp'), ('tablespoon', 'Tbsp'), ('cup', 'cup'), ('pint', 'pint'), ('quart', 'quart'), ('gallon', 'gallon')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jrecipes.ingredient')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='nutritional_info',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='type_enum',
        ),
        migrations.AddField(
            model_name='recipe',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jrecipes.instructionstep'),
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='NutritionalInfo',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_list',
            field=models.ManyToManyField(blank=True, help_text='Select an IngredientListItem for this recipe', to='jrecipes.ingredientlistitem'),
        ),
    ]
