# Generated by Django 4.0.4 on 2023-01-03 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0015_ingredient_ingredientlistitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlistitem',
            name='ingredient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jrecipes.ingredient'),
        ),
    ]
