# Generated by Django 4.0.4 on 2023-01-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0019_alter_ingredientlistitem_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='allergen',
            new_name='allergens',
        ),
    ]
