# Generated by Django 4.0.4 on 2023-01-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0021_remove_recipe_instructions_recipe_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='jrecipes.instructionstep'),
            preserve_default=False,
        ),
    ]
