# Generated by Django 4.0.4 on 2023-01-03 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0023_remove_recipe_instructions_recipe_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionstep',
            name='sub_steps',
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='title',
            field=models.CharField(default='DEFAULT TITLE BABAY', max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jrecipes.instructionstep'),
        ),
        migrations.CreateModel(
            name='InstructionSubStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jrecipes.instructionstep')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
