# Generated by Django 4.0.4 on 2023-01-03 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0024_remove_instructionstep_sub_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionsubstep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_steps', to='jrecipes.instructionstep'),
        ),
    ]
