# Generated by Django 4.0.4 on 2023-01-04 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0025_alter_instructionsubstep_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='jrecipes.recipe'),
            preserve_default=False,
        ),
    ]
