# Generated by Django 4.0.4 on 2023-01-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0026_remove_recipe_instructions_instructionstep_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientlistitem',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_list',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='jrecipes.ingredientlistitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientlistitem',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_list_item', to='jrecipes.recipe'),
            preserve_default=False,
        ),
    ]
