# Generated by Django 4.0.4 on 2023-01-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jrecipes', '0029_remove_ingredient_ingredient_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructionstep',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='instructionsubstep',
            options={'ordering': ['id']},
        ),
    ]
