# Generated by Django 4.0.4 on 2022-04-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('portion_size', models.IntegerField()),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('additional_notes', models.TextField()),
                ('nutritional_info', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
